### ISSUE TITLE
Cannot build Java 18

### ISSUE THREAD

**Issue by Ygarr** [MichaelGatesDev/ExifExplorer#2]
` Execution default-cli of goal com.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path %JAVA_HOME%`
tested on different JDK

**Comment by MichaelGatesDev** [comment]
I should probably archive this repo as I only used it as a proof-of-concept for a school project. Basically the reason you're having that error is because Java decided to split JFX (used for the GUI) apart from the JDK and instead ships it as a separate library. This project was built on Java 8 or a version near that, when JFX was still packaged with the JDK. You could try using a version of the JDK around 8 to see if it works. 

I can't offer any more support than that, though.
